pipeline {
    agent any

    environment {
        IMAGE_NAME = "yashvardhanjangid/somefrontend" // lowercase is safer
        IMAGE_TAG = "1.0.0"
    }

    stages {

        stage('Try') {
            steps {
                echo "hello i have startyed"
            }
        }
    stage('Build Docker Image') {
    steps {
        script {
            echo "Building Docker image... adding path to current directory"
            dir('todo-app-frontend-main') {
                def customImage = docker.build("${IMAGE_NAME}:${IMAGE_TAG}")
                env.IMAGE_ID = customImage.id
            }
        }
    }
}
        stage('Checkout Code') {
            steps {
                git branch: 'branch1', url: 'https://github.com/YRJCodes/somefrontendJenkins.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    echo "Building Docker image..."
                    def customImage = docker.build("${IMAGE_NAME}:${IMAGE_TAG}")
                    env.IMAGE_ID = customImage.id
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', 'dockerCreds') {
                        docker.image("${IMAGE_NAME}:${IMAGE_TAG}").push()
                    }
                }
            }
        }
    }

    post {
        success { echo "Docker image successfully built and pushed 🚀" }
        failure { echo "Pipeline failed ❌" }
    }
}
